### ISSUE TITLE
Check the top-level render call using <Styled(div)>

### ISSUE THREAD

**Issue by duckscofield** [vertexbz/storybook-addon-react-live-edit#10]
After I use this addon, console pop these message...

<img width="850" alt="Google Chrome Canary__ScreenShot_May 14 2019 at 3 26 19 PM" src="https://user-images.githubusercontent.com/8048120/57678885-b5c27680-765c-11e9-8339-1860c4aff7f8.png">

**Comment by vertexbz** [comment]
Should be resolved in 2.0.4. Sorry for unavailability.
