### ISSUE TITLE
How to add withLiveEditScope at the top level?

### ISSUE THREAD

**Issue by totsteps** [vertexbz/storybook-addon-react-live-edit#13]
Is it possible to add `withLiveEditScope` at the top level by which each component becomes editable, so that I don't have to add Decorator for each Component.

**Comment by beizhedenglong** [comment]
@gagan0723 You config this in `config.js` of storybooks like this https://github.com/beizhedenglong/react-hooks-lib/blob/master/.storybook/config.js#L7

**Comment by totsteps** [comment]
Thanks for the help.
