### ISSUE TITLE
About the error "Module not found: Error: Can't resolve 'a-apackage'"

### ISSUE THREAD

**Issue by mozgbrasil** [vertexbz/storybook-addon-react-live-edit#14]
About the error "Module not found: Error: Can't resolve 'a-apackage'"

Hello my friends

As per images

I followed the registration process of the following addon

https://github.com/vertexbz/storybook-addon-react-live-edit

But in the terminal we see the error returned

Can you help me ?

![Captura de tela de 2019-09-13 18-54-25](https://user-images.githubusercontent.com/17202780/64896926-ebea2400-d657-11e9-8f29-f750dc4af752.png)

**Comment by oleksii-ivanov** [comment]
Hi **mozgbrasil**,  seems that 'a-apackage' didn't exist, and it's just placeholder for component that you need to wrap

**Comment by mozgbrasil** [comment]
Good Morning

Thank you my brother
