### ISSUE TITLE
Addon shows up at the same time as other addons

### ISSUE THREAD

**Issue by storywr** [vertexbz/storybook-addon-react-live-edit#2]
I noticed that this addon shows up at the same time as other addons. It looks like the problem can be traced back to a missing active prop in the render method of the register.js file. As explained in the storybook docs: https://storybook.js.org/addons/writing-addons/

>To avoid having addons show up at the same time as each other, each addon should be aware of the active prop sent by Storybook and only render addon when active is true.

`render: ({ active }) => <Notes channel={channel} api={api} active={active} />`

**Comment by vertexbz** [comment]
Hi! Thanks for reporting. It looks like the active prop was introduced with sb4 and nothing is sent to render function in sb3. I added fallback for sb3 on my active-prop branch. could you take a look if it does resolve the issue?

**Comment by storywr** [comment]
Hey, I initially approached the issue the same way but it looks like LiveEditor then doesn't know to re-render when switching between addons. I was able to fix on my branch by actually passing the `active` prop to the `LiveEditor` component and then updating the `componentDidUpdate` method as follows:

```jsx
setCodeMirror = (theme: ?string) => {
    this.codeMirror = CodeMirror(this.codeMirrorRef, { mode: 'jsx', theme });
    this.codeMirror.on('change', this.codemirrorValueChanged);
}

componentDidUpdate(prevProps) {
    const theme = themeNameToVarName(this.state.theme) in themes ? this.state.theme : 'default';

    if (prevProps.active !== this.props.active) this.setCodeMirror(theme)
    if (this.state.code !== null) {
        if (!this.codeMirror) {
            this.setCodeMirror(theme)
        } else {
            this.codeMirror.setOption('theme', theme);
        }
        // $FlowIgnore
        this.codeMirror.setValue(this.state.code);
    } else {
        this.codeMirror = null;
    }
}
```

This way it checks to update based on changes in the `active` prop. I then added this line to the render method of `LiveEditor`:

```jsx
 if (!this.props.active) return null
```

**Comment by vertexbz** [comment]
Thanks for a clue, based on your code I added active prop support in a bit different way and performed a few tests - it seems to work fine enabling disabling this section for me, could you check my active-prop branch and tell if it does resolve your issue as well?

**Comment by storywr** [comment]
Yes, that seems to have resolved it. Thanks for the quick update and thanks for building this great tool!

**Comment by vertexbz** [comment]
Cheers and thanks for your help :) version 2.0.2 is just released
