### ISSUE TITLE
React is not defined?

### ISSUE THREAD

**Issue by KornelSzaltanowicz** [vertexbz/storybook-addon-react-live-edit#4]
Am I missing something in config, cause I got beautiful "React is not defined error" 
![screen shot 2019-01-06 at 12 39 33](https://user-images.githubusercontent.com/7700156/50735498-67820000-11b0-11e9-901d-98e44c972344.png)

Whole storybook works fine except this addon...

Storybook: 4.1.4
React 16.4.1
babel-core: 6.23.3

My config: 
![screen shot 2019-01-06 at 12 42 47](https://user-images.githubusercontent.com/7700156/50735532-e5460b80-11b0-11e9-8608-e6003c29d3d1.png)
![screen shot 2019-01-06 at 12 42 58](https://user-images.githubusercontent.com/7700156/50735533-eaa35600-11b0-11e9-90ff-46824776b715.png)
![screen shot 2019-01-06 at 12 43 34](https://user-images.githubusercontent.com/7700156/50735535-eecf7380-11b0-11e9-8ea5-d4ce1e6baef4.png)

**Comment by KornelSzaltanowicz** [comment]
Any ideas what may be wrong?

**Comment by barakplasma** [comment]
I had the same error, and it results from incomplete documentation.

You need to provide `React` to withLiveEditScope like the example: https://github.com/vertexbz/storybook-addon-react-live-edit/blob/0d77f9baca3da66aae6d1b30737991c690ef2e0b/example/index.js#L9

We should open a PR to update the documentation at https://github.com/vertexbz/storybook-addon-react-live-edit/blob/master/README.md#add-withliveeditscope-story-decorator
