### ISSUE TITLE
Editing causes re-render of editor

### ISSUE THREAD

**Issue by jonnyasmar** [vertexbz/storybook-addon-react-live-edit#9]
I'm not sure, but this may be a Storybook v5 issue:

Whenever I edit code in the LiveEditor (I've hacked around the theme issue in https://github.com/vertexbz/storybook-addon-react-live-edit/issues/8 for now), it seems like the editor rerenders, resets its contents to the original provided to `withLiveEdit`, and moves the cursor back to the beginning of the editor.

**Comment by adberard** [comment]
How did you hacked around #8 ?

**Comment by jonnyasmar** [comment]
To be completely honest, I don't recall -- I haven't looked into this much since then.

I believe I just jumped into the source code at `/Users/karolwons/ui-docs-next/node_modules/storybook-addon-react-live-edit/dist/component/LiveEditor` and changed the reference to `@storybook/components/dist/theme` to point to the newer theme. I'm not on my work machine at the moment though and don't recall exactly where that is.

**Comment by vertexbz** [comment]
Should be resolved in 2.0.4. Sorry for unavailability.
